packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms # default 320ms. Time spent per adv channel
    window: 30ms # default 30ms. Time spent listening during interval.
    # active: false

logger:
  baud_rate: 0 # disable serial uart logging

button:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: status
    name: "Status"
    
sensor:
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic
    disabled_by_default: false
    force_update: false
    unit_of_measurement: dBm
    accuracy_decimals: 0
    device_class: signal_strength
    state_class: measurement

wifi:
#   enable_btm: true
  fast_connect: true
  power_save_mode: none
#   enable_rrm: true
