packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms # default 320ms. Time spent per adv channel
    window: 160ms # default 30ms. Time spent listening during interval.
    # active: false

logger:
  baud_rate: 0 # disable serial uart logging

button:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: status
    name: "Status"
# wifi:
#   fast_connect: true
# enable_btm: true
# enable_rrm: true
