substitutions:
  garage_door_close_warning_duration: "2s"
  warning_tone_rtttl: ${mario}

binary_sensor:
  - platform: status
    name: Status

web_server: !remove

wifi:
  enable_btm: true
  fast_connect: true
  enable_rrm: true
